pattern_cols: 10
pattern_rows: 7
center_distance_mm: 40

R_gimbal2imubody: [1, 0, 0, 0, 1, 0,  0, 0, 1]

camera_name: "hikrobot"
exposure_ms: 3
gain: 10.0
vid_pid: "2bdf:0001"

#####-----cboard参数-----#####
quaternion_canid: 0x01
bullet_speed_canid: 0x110
send_canid: 0xff
can_interface: "can0"

# 重投影误差: 0.0605px
camera_matrix: [1730.7107341973649, 0, 728.97473270583646, 0, 1735.1131442449105, 455.94964292375778, 0, 0, 1]
distort_coeffs: [-0.097028190516311175, 0.18753197920473369, -0.003793088668409072, 0.0023961173264070708, 0]