pattern_cols: 10
pattern_rows: 7
center_distance_mm: 40

R_gimbal2imubody: [1, 0, 0, 0, 1, 0,  0, 0, 1]

camera_name: "hikrobot"
exposure_ms: 3
gain: 10.0
vid_pid: "2bdf:0001"

#####-----cboard参数-----#####
quaternion_canid: 0x01
bullet_speed_canid: 0x110
send_canid: 0xff
can_interface: "can0"

# 重投影误差: 0.0568px
camera_matrix: [1858.7894038668321, 0, 708.61996779339825, 0, 1857.5227736505669, 508.76004836399375, 0, 0, 1]
distort_coeffs: [-0.061381582603303814, 0.13766372045631334, -0.0012558735456410738, -0.0011721148047512437, 0]